### ISSUE TITLE
Hey again.

### ISSUE THREAD

**Issue by guga330** [Tommrodrigues/WiFiCrackPy#1]
Hey Tom. Talked to you a few days ago. Was wondering if you could also create a repository with the old WiFiCrack. I accidentally uninstalled it. I found it easier to capture the handshake with the older version because it was more organized when it scanned the nearby networks. Thank you. Keep up the good work.
OBS: the version with python disorganized the wifi info --> https://ibb.co/3NcxVtQ
OBS: also there is an error on the handshake, don't know why --> https://ibb.co/DYTBjmc

**Comment by Tommrodrigues** [comment]
Hi there,

Thanks for reporting the issue with the parsing of scanned networks - you were hitting problems because of the way the script handled networks with spaces in their names. The issue should now be resolved, and I would now recommend using this new script rather than the old one.

The error you posted seems to be a directory issue, please make sure you `cd` into the directory of the script before running it as per the `README.md`

If you would still like to use the old WiFiCrack script however, the repository has not been taken down, it is still available [here](https://github.com/Tommrodrigues/WiFiCrack)
